### ISSUE TITLE
python subprocess.run enoexec

### ISSUE THREAD

**Issue by Arwalk** [jart/cosmopolitan#120]
Hey there. Fantastic work.
I have an edge case that i can't figure out by myself. This is minimal but i have a feeling it could help later to solve it.

I've wrapped a library i work on around a "cosmopolitanized" executable, to be able to distribute a multi-os python package wrapping up this library.

Everything works perfectly fine: my development environment uses WSL2 for compiling the executable, and runs all the python tests in windows. 

Impossible to make my tests runs in a CI environment using docker though. I've figured out simple steps to reproduce this behavior.

1. start an alpine:latest docker container (tested on ubuntu latest with same behavior) in interactive mode
2. install gcc and python3 with `apk --no-cache add gcc python3`
3. follow the instructions in the "Getting Started" part of this repository to build a simple "cosmopolitanized" hello.com executable
4. execute this simple python (3) script

```python
import subprocess

subprocess.run(["./hello.com"])
```

This gives us this result:

```
Traceback (most recent call last):
  File "run_python.py", line 4, in <module>
    subprocess.run(["./hello.com"])
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './hello.com'
```

The interesting part is that if i manually call `hello.com` from any shell in the docker, the next time i run the python script, everything works fine. This behaviour only occurs in docker: i've done the same steps in a WSL2 alpine setup, and the python script was ok on the first call. (same in Ubuntu WSL2, with the same strange behavior in Ubuntu docker)

I suppose there is something very subtle here that makes python unable to trigger the first run of the executable (which AFAIK provokes a change in the executable itself to be able to run properly on the current OS), that only happens in docker.

In itself, it's not much of a problem: i can force a run of my executable before running my python tests in my CI environment. But i have a feeling i won't be the only one having this problem, and that it could hint at something useful for this project.

**Comment by jart** [comment]
I'll look into upstreaming a patch with Python as soon as #88 is merged.
