### ISSUE TITLE
Compiling all of cosmopolitan on macOS

### ISSUE THREAD

**Issue by ghaerr** [jart/cosmopolitan#375]
Hello @jart,

I'm continuing the discussion from https://github.com/jart/cosmopolitan/issues/227#issuecomment-1077806881, but am opening a new issue, so as not to be off-topic. I hope that's ok, and excuse in advance this long report.

I (finally) now have almost the entire repo compiling (and all .com files produced seemingly working) under macOS. I'd like to help contribute to Cosmopolitan but need to be able to build everything under macOS, since I don't have easy everyday access to Linux. And of course, a huge motivation is to play more with blinkenlights.com, which now is working and compiling from scratch on macOS :)

Rather than immediately produce a PR, I thought to get your input as to various issues found during the port. At present, some of the fixes required hacks, which will want to be fixed differently. I will describe each issue in more detail below using a bullet point.

I installed a pre-compiled [homebrew version of Rich Felker's musl-cross-make x86_64-linux-musl-gcc](https://github.com/FiloSottile/homebrew-musl-cross) first, which installs the compiler in /usr/local/bin on macOS. Using this version could be helpful, if it were ever decided to build the Linux and macOS compilers from the same source and build scripts.

Second, it was found that macOS (Catalina) is running GNU make 3.81, which silently ignores the `$(file ...)` function, used to prepare argument lists all over. Installing [homebrew version of make 4.3](https://stackoverflow.com/questions/43175529/updating-make-version-on-mac) and then executing `export PATH=/usr/local/opt/make/libexec/gnubin:$PATH` solved that problem.

These macOS updates then allowed a small diff and a few other changes to compile most of Cosmopolitan.

Here's the entire diff:
```
diff --git a/build/config.mk b/build/config.mk
index 17827a02e..ee34147f0 100644
--- a/build/config.mk
+++ b/build/config.mk
@@ -308,6 +308,35 @@ OBJDUMP = llvm-objdump
 ADDR2LINE = llvm-addr2line
 endif

+# macOS - options copied from Tiny Metallic Unix Mode
+ifeq ($(MODE), macOS)
+TOOLPREFIX=/usr/local/bin/x86_64-linux-musl-
+AS = $(TOOLPREFIX)as
+CC = ./gcc
+GCC = ./gcc
+CXX = $(TOOLPREFIX)g++
+CXXFILT = $(TOOLPREFIX)llvm-c++filt
+LD = $(TOOLPREFIX)ld.bfd
+NM = $(TOOLPREFIX)nm
+STRIP = $(TOOLPREFIX)strip
+OBJCOPY = $(TOOLPREFIX)objcopy
+OBJDUMP = $(TOOLPREFIX)objdump
+ADDR2LINE = $(TOOLPREFIX)addr2line
+CONFIG_CPPFLAGS +=     \
+   -DTINY          \
+   -DNDEBUG        \
+   -DTRUSTWORTHY       \
+   -DSUPPORT_VECTOR=251
+CONFIG_CCFLAGS +=      \
+   -Os         \
+   -fno-align-functions    \
+   -fno-align-jumps    \
+   -fno-align-labels   \
+   -fno-align-loops
+TARGET_ARCH ?=         \
+   -msse3
+endif
+
 # ANSI Mode
 #
 # These flags cause GCC to predefine __STRICT_ANSI__. Please be warned
diff --git a/build/definitions.mk b/build/definitions.mk
index 7a08e72a7..b06aa4c9f 100644
--- a/build/definitions.mk
+++ b/build/definitions.mk
@@ -59,13 +59,17 @@ AR = build/bootstrap/ar.com
 PKG = build/bootstrap/package.com
 MKDEPS = build/bootstrap/mkdeps.com
 ZIPOBJ = build/bootstrap/zipobj.com
-AS = o/third_party/gcc/bin/x86_64-linux-musl-as
-CC = o/third_party/gcc/bin/x86_64-linux-musl-gcc
+#AS = o/third_party/gcc/bin/x86_64-linux-musl-as
+AS = /usr/local/bin/x86_64-linux-musl-as
+#CC = o/third_party/gcc/bin/x86_64-linux-musl-gcc
+CC = ./gcc
 CXX = o/third_party/gcc/bin/x86_64-linux-musl-g++
 CXXFILT = o/third_party/gcc/bin/x86_64-linux-musl-c++filt
-LD = o/third_party/gcc/bin/x86_64-linux-musl-ld.bfd
+#LD = o/third_party/gcc/bin/x86_64-linux-musl-ld.bfd
+LD = /usr/local/bin/x86_64-linux-musl-ld.bfd
 NM = o/third_party/gcc/bin/x86_64-linux-musl-nm
-GCC = o/third_party/gcc/bin/x86_64-linux-musl-gcc
+#GCC = o/third_party/gcc/bin/x86_64-linux-musl-gcc
+GCC = ./gcc
 STRIP = o/third_party/gcc/bin/x86_64-linux-musl-strip
 OBJCOPY = o/third_party/gcc/bin/x86_64-linux-musl-objcopy
 OBJDUMP = o/third_party/gcc/bin/x86_64-linux-musl-objdump
diff --git a/build/sanitycheck b/build/sanitycheck
index c2da2d263..235d10af4 100755
--- a/build/sanitycheck
+++ b/build/sanitycheck
@@ -9,7 +9,7 @@
 #   This script is launched at the start of Makefile to detect if
 #   binfmt_misc was tuned to launch 'MZ' shell scripts under WINE

-if [ x`uname -s` != xLinux ]; then
+if [ x`uname -s` != xLinux -a x`uname -s` != xDarwin ]; then
   cat <<'EOF' >&2

 ERROR
diff --git a/test/libc/release/emulate.sh b/test/libc/release/emulate.sh
index cb9152877..eac0ec289 100755
--- a/test/libc/release/emulate.sh
+++ b/test/libc/release/emulate.sh
@@ -8,6 +8,10 @@ if [ "$MODE" = opt ] || [ "$MODE" = optlinux ]; then
   exit
 fi

+if [ "$MODE" = macOS ]; then
+  exit  # TODO
+fi
+
 # smoke test userspace binary emulation
 CMD="o/$MODE/tool/build/blinkenlights.com.dbg o/$MODE/examples/hello.com"
 if OUTPUT="$($CMD)"; then
diff --git a/third_party/mbedtls/mbedtls.mk b/third_party/mbedtls/mbedtls.mk
index 030e78dd5..e8de2d696 100644
--- a/third_party/mbedtls/mbedtls.mk
+++ b/third_party/mbedtls/mbedtls.mk
@@ -74,8 +74,6 @@ o/$(MODE)/third_party/mbedtls/shiftright2-avx.o:          \
 o/$(MODE)/third_party/mbedtls/zeroize.o:               \
            OVERRIDE_CFLAGS +=              \
                -O3                 \
-               -x-no-pg                \
-               -fomit-frame-pointer            \
                -foptimize-sibling-calls

 THIRD_PARTY_MBEDTLS_LIBS = $(foreach x,$(THIRD_PARTY_MBEDTLS_ARTIFACTS),$($(x)))
```
- A "MODE=macOS" was added to config.mk, but that can't fully work, since definitions.mk is using CC= and GCC= values in other macros (OBJECTIFY etc) before config.mk is included. 

Not sure how you'd like to handle this, but the latter macros in definitions.mk should be executed after config.mk, or perhaps have the CC= lines moved from definitions.mk to config.mk and have config.mk included first.

Also, I'm not sure the options I've selected for macOS (which are copies of the "MODE=tinynowin" mode) are proper for macOS; in particular the -DSUPPORT_VECTOR=251 option. For that matter, I haven't found explanations of the specific differences of each mode.

- Compile.com adds "-no-canonical-prefixes" to the CC compile line automatically, with no way to remove it. This causes an `excecvp error: cc1 not found`, with seemingly no option to turn prefixes back on. I tried all sorts of ways around that with external pathing, but without a compiler "-canonical-prefixes" to turn back on, I suggest removing this option being automatically added by compile.com.

A total hack workaround for the time being required setting the compiler to `./gcc` (which allows compile.com to work magic based on gcc being a part of the filename, but yet removing -no-canonical-prefixes. There's the hack ./gcc shell script:
```
args=("$@")
for ((i=0; i<"${#args[@]}"; ++i)); do
    case ${args[i]} in
        -no-canonical-prefixes) unset args[i]; break;;
    esac
done
exec /usr/local/bin/x86_64-linux-musl-gcc "${args[@]}"
```
- A possible compiler incompatibility was noticed in third_party/mbedtls/zeroize.c, where the `-x-no-pg` option (a non-standard option supposed to turn off -pg?) is being interpreted as a language option and giving the error "no such language -no-pg". Thus, both that and the -fomit-frame-pointer options had to be (temporarily) removed. This is likely incorrect, but I'm not sure what to do.

- The test/libc/release/emulate.sh was modified to just exit, since for reasons I don't understand yet, all \*.com.dbg executables are broken - macOS errors with "cannot execute binary file". Is this because I possibly have -DSUPPORT_VECTOR=251 set to the wrong value for macOS?

With these changes, the cosmopolitan builds all libraries, headers and examples, with all .com files working, up to third_party/chibicc/test/common.chibicc.o, which fails due to chibicc.com.dbg not being executable.

I'd be happy to help get Cosmopolitan firmly building on macOS, if you're willing. You have an amazing project! How would you like to proceed?

Thank you!

**Comment by jart** [comment]
I support this. It would need to be community maintained for the time being. The biggest thing I recommend doing is creating a shell script in the build folder that rewrites the cc flags so clang is happy. That way you can send PRs quickly. I won't merge PRs that change the binary bootstrap blob for compile.com.

**Comment by jart** [comment]
There's an llvm section in config.mk. Would you be interesting in maintaining that? In other words, you'd put something like `make MODE=darwin` or `make MODE=llvm`. We use the `-x-no-pg` flag because sometimes it's needed to turn that flag off. It's recognized by `compile.com`. You can do what we used to do. See its predecessor https://github.com/jart/cosmopolitan/blob/c91b3c50068224929cd4d3ddf36c5a10254cbd9c/build/compile

**Comment by ghaerr** [comment]
Hello @jart,

> There's an llvm section in config.mk. Would you be interesting in maintaining that?

Yes, I'd be happy to maintain the macOS port for you. I was thinking that this might be done in two steps: the first, getting [Rich Felker's gcc musl-based cross compiler](https://github.com/FiloSottile/homebrew-musl-cross) building Cosmopolitan, and then in a second step considering the issues with getting llvm building and linking properly. The advantage of the first step is that the compiled objects should be very close if not identical to the Linux versions, and that the ld.bfd linker can be used, rather than having to deal with Apple's llvm-ld at first.

I have Cosmopolitan building now on macOS, using `make MODE=darwin`. There are still some small issues when restarting the make, for instance:
```
make MODE=darwin
♥cosmo
error: "usr/share/zoneinfo/" (o/darwin/libc/time/localtime.o) not defined by direct deps of o/darwin/libc/time/time.a.pkg
	o/darwin/libc/calls/syscalls.a.pkg
```
After sorting these issues out, I can submit a PR for your consideration.

> We use the -x-no-pg flag because sometimes it's needed to turn that flag off. It's recognized by compile.com.

Thanks, I didn't realize the flag was recognized by compile.com. I'm looking into why compile.com isn't turning off the -pg flag in this case, there is some special handling by compile.com looking at the basename of the compiler. In my case, the compiler name is the same, except the path to it is /usr/local/bin, rather than o/thirdparty/gcc/bin.

> You can do what we used to do. See its predecessor https://github.com/jart/cosmopolitan/blob/c91b3c50068224929cd4d3ddf36c5a10254cbd9c/build/compile

Got it. I would like to be able to solve this issue without having to resort to using a fancy shell script to run the compiler, since there is already compile.com. There are only couple small issues remaining.

Thank you!

**Comment by jart** [comment]
We're already using musl-cross-make embedded binaries to build on Linux. If that runs on Darwin then it'll probably help. If you don't want to do the shell script then would you like me to modify compile.com so that it filters the flags appropriately if `IsXnu()`? I guess what you could do is send me a PR that changes compile.c and then I could submit another change that rebuilds the binary.

**Comment by ghaerr** [comment]
> would you like me to modify compile.com so that it filters the flags appropriately if IsXnu()? I guess what you could do is send me a PR that changes compile.c and then I could submit another change that rebuilds the binary.

That would be great! I will post a minimal PR shortly. I have the darwin build working now.

**Comment by ghaerr** [comment]
Hello @jart,

Things are looking a lot better regarding using macOS for compilation of Cosmopolitan. In short, the entire repo can be made to compile with just one change to `build/definitions.mk` (using [Rich Felker's x86_64-musl-gcc compiler](https://github.com/FiloSottile/homebrew-musl-cross)), although later on the build fails in some of the python tests.

I am going to close #386, as much has been done since April for macOS cross-compilation. Only the following patch is required at this point:
```
diff --git a/build/definitions.mk b/build/definitions.mk
index 4b4f1cd22..19788da32 100644
--- a/build/definitions.mk
+++ b/build/definitions.mk
@@ -86,6 +86,20 @@ OBJCOPY = o/third_party/gcc/bin/x86_64-pc-linux-gnu-objcopy.exe
 OBJDUMP = o/third_party/gcc/bin/x86_64-pc-linux-gnu-objdump.exe
 ADDR2LINE = $(PWD)/o/third_party/gcc/bin/x86_64-pc-linux-gnu-addr2line.exe
 else
+UNAME := $(shell /usr/bin/uname)
+ifeq ($(UNAME), "Darwin")
+AS = x86_64-linux-musl-as
+CC = x86_64-linux-musl-gcc
+CXX = x86_64-linux-musl-g++
+CXXFILT = x86_64-linux-musl-c++filt
+LD = x86_64-linux-musl-ld.bfd
+NM = x86_64-linux-musl-nm
+GCC = x86_64-linux-musl-gcc
+STRIP = x86_64-linux-musl-strip
+OBJCOPY = x86_64-linux-musl-objcopy
+OBJDUMP = x86_64-linux-musl-objdump
+ADDR2LINE = x86_64-linux-musl-addr2line
+else
 IGNORE := $(shell build/bootstrap/unbundle.com)
 AS = o/third_party/gcc/bin/x86_64-linux-musl-as
 CC = o/third_party/gcc/bin/x86_64-linux-musl-gcc
@@ -99,6 +113,7 @@ OBJCOPY = o/third_party/gcc/bin/x86_64-linux-musl-objcopy
 OBJDUMP = o/third_party/gcc/bin/x86_64-linux-musl-objdump
 ADDR2LINE = $(PWD)/o/third_party/gcc/bin/x86_64-linux-musl-addr2line
 endif
+endif
 
 export ADDR2LINE
 export LC_ALL
```
Would you like me to post that as a PR?

Other items to note:
- Typing `make` using GNU make v3.81 fails with the following error:
```
zorg:cosmopolitan greg$ make
♥cosmo
third_party/mbedtls/test/test.mk:408: *** multiple target patterns.  Stop.
```
Running `build/bootstrap/make.com` works.

- The build eventually fails with the following python-related test errors:
```
zorg:cosmopolitan greg$ !build
build/bootstrap/make.com 
♥cosmo
...........E....E......
======================================================================
ERROR: test_fieldstorage_multipart_maxline (__main__.CgiTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zip/.python/test/test_cgi.py", line 324, in test_fieldstorage_multipart_maxline
    check('x' * (maxline - 1))
  File "/zip/.python/test/test_cgi.py", line 322, in check
    self.assertEqual(gen_result(data, environ),
  File "/zip/.python/test/test_cgi.py", line 109, in gen_result
    form = cgi.FieldStorage(fp=fake_stdin, environ=environ, encoding=encoding)
  File "/zip/.python/cgi.py", line 569, in __init__
    self.read_multi(environ, keep_blank_values, strict_parsing)
  File "/zip/.python/cgi.py", line 744, in read_multi
    self.encoding, self.errors, max_num_fields, self.separator)
  File "/zip/.python/cgi.py", line 571, in __init__
    self.read_single()
  File "/zip/.python/cgi.py", line 765, in read_single
    self.read_lines()
  File "/zip/.python/cgi.py", line 794, in read_lines
    self.read_lines_to_outerboundary()
  File "/zip/.python/cgi.py", line 870, in read_lines_to_outerboundary
    self.__write(odelim + line)
  File "/zip/.python/cgi.py", line 802, in __write
    self.file = self.make_file()
  File "/zip/.python/cgi.py", line 919, in make_file
    return tempfile.TemporaryFile("wb+")
  File "/zip/.python/tempfile.py", line 597, in TemporaryFile
    fd = _os.open(dir, flags2, 0o600)
OverflowError: signed integer is greater than maximum

======================================================================
ERROR: test_fieldstorage_readline (__main__.CgiTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zip/.python/test/test_cgi.py", line 240, in test_fieldstorage_readline
    f = TestReadlineFile(tempfile.TemporaryFile("wb+"))
  File "/zip/.python/tempfile.py", line 597, in TemporaryFile
    fd = _os.open(dir, flags2, 0o600)
OverflowError: signed integer is greater than maximum

----------------------------------------------------------------------
Ran 23 tests in 0.016s
```
